name: mele_shop

services:
  db:
    image: postgres:16-alpine
    container_name: mele_shop_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: mele_shop_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      POSTGRES_HOST: db
    volumes:
      - ../myshop/media:/app/media
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  celery:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: mele_shop_celery
    command: celery -A myshop worker -l info -Q celery,manual_queue,front_rubbish
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      POSTGRES_HOST: db
    volumes:
      - ../myshop/media:/app/media
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

  flower:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: mele_shop_flower
    command: celery -A myshop flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      rabbitmq:
        condition: service_healthy
      celery:
        condition: service_started
    restart: unless-stopped

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: mele_shop_stripe_cli
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://web:8000/en/payment/webhook/ --events checkout.session.completed
    env_file:
      - .env
    depends_on:
      web:
        condition: service_started
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mele_shop_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
