# Generated by Django 4.1.13 on 2026-07-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('cart_adds_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('paid_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shop.product')),
            ],
            options={
                'verbose_name': 'product stats',
                'verbose_name_plural': 'product stats',
            },
        ),
    ]
